language: python
matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true

install:
    - pip install -r requirements/dev_requirements.txt

script:
    - ./run_tests.sh

after_success:
  - codecov
