language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: 3.9
      dist: xenial
      sudo: true
    - python: 3.10.1
      dist: focal
      sudo: true

install:
    - pip install -r requirements/dev_requirements.txt

script:
    - ./scripts/run_tests.sh

after_success:
  - codecov
